name: Deploy bot to ec2

on: push
#  push:
#    branches:
#      - master

jobs:
    build_and_push:
        name: Build and Push image
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: cachix/install-nix-action@v10
          with:
            skip_adding_nixpkgs_channel: true
        - run: |
            make image
