name: Deploy bot to ec2

on: push
#  push:
#    branches:
#      - master

jobs:
    build_and_push:
        name: Build and Push image
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: cachix/install-nix-action@v10
          with:
            skip_adding_nixpkgs_channel: true
        - run: |
             make docker-image
          env: 
            NIX_PATH: nixpkgs=https://github.com/nixos/nixpkgs-channels/tarball/c9d124e39dbeefc53c7b3e09fbfc2c26bcbd4845

