name: Deploy bot to ec2

#on:
#  push:
#    branches:
#      - main

jobs:
    build_and_push:
        name: Build and Push image
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: cachix/install-nix-action@v10
          with:
            skip_adding_nixpkgs_channel: true
        - name: Setup SSH Key
          env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_GITHUB_KEY }}"
        - name: Docker login
          run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u jeovazero --password-stdin
        - name: Build and push image to docker hub
          run: |
             make docker-image-and-push
          env: 
            NIX_PATH: nixpkgs=https://github.com/nixos/nixpkgs-channels/tarball/7badbf18c45b7490d893452beb8950d966327831
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        - name: Update service in EC2
          uses: appleboy/ssh-action@ffff33f8fe0318345a4f00f0e847325954b2a3ed
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            envs: TAG
            script: |
                docker pull $TAG
                docker service update nano_hs_stack_bot --image $TAG
